### ISSUE TITLE
crash when decompressing a P3D file

### ISSUE THREAD

**Issue by Seven377** [MEPP-team/MEPP#39]
A P3D file is obtained after compressing a mesh using MEPP.  I just try to decompress this P3D file and then compare compression rates(bits per vertex) at each different LoDs, but it crashed. How can I obtain corresponding compression rates ?

**Comment by mtola** [comment]
Hello,
This component is a rather old one.
We have a new (but private) component.
Can you please write to me (martial.tola@liris.cnrs.fr) and please introduce yourself a little bit ;-)
Thank you...
